import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Client } from 'appwrite';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}


const appwrite = new Appwrite();
appwrite
  .setEndpoint('https://cloud.appwrite.io/v1') // Replace with your Appwrite endpoint
  .setProject('646a274819ca61ea5325') // Replace with your Appwrite project ID
  .setKey('b047f305b96ca3072a5c5bf290d27852c8275af33433ad177c524a705d667fde807838b18e6eccbdc7f1f03c6e5f4cddb8e841222fdbc873e59b666864a79aa8afd43725d15124b11ca136fac6785d637c7ce789ea6c6c056d855bfed19d88dcfec5d10cccf8abc3725b3811482523708ecd1b421b59fedd4eb91c9a0fc7530b'); // Replace with your Appwrite API key

// Add event listener to save buttons
const saveButtons = document.querySelectorAll('.save-btn');
saveButtons.forEach((button) => {
  button.addEventListener('click', () => {
    const textarea = button.previousElementSibling;
    const content = textarea.value;
    
    saveContent(content);
  });
});


function saveContent(content) {
 
  appwrite
    .call('collections.createDocument', {
      collectionId: 'YOUR_COLLECTION_ID', 
      data: {
        content: content,
      },
    })
    .then((response) => {
      console.log('Content saved:', response);
    })
    .catch((error) => {
      console.error('Error saving content:', error);
    });
}

const addButton = document.getElementById('add-btn');
addButton.addEventListener('click', () => {
  const textarea = document.createElement('textarea');
  const saveButton = document.createElement('button');
  saveButton.classList.add('save-btn');
  saveButton.textContent = 'Save';
  
  const textareaContainer = document.createElement('div');
  textareaContainer.classList.add('textarea-container');
  textareaContainer.appendChild(textarea);
  textareaContainer.appendChild(saveButton);
  
  const parent = document.querySelector('body');
  parent.insertBefore(textareaContainer, addButton);
});
